url: https://www.henrikbecker.net
permalink: pretty
excerpt_separator: <!--more-->

collections:
 recipes:
  output: true
  permalink: /:name/

defaults:
 - scope:
    path: ""     
    type: recipes
   values:
    layout: recipe
 - scope: 
    path: ""
   values: 
    layout: default
