permalink: pretty
excerpt_separator: <!--more-->

collections:
 recipes:
  output: true

defaults:
 - scope:
    path: ""     
    type: recipes
   values:
    layout: recipe
 - scope: 
    path: ""
   values: 
    layout: default
