name: Build and Publish
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install bundler
      - run: bundler install
      - run: bundle exec jekyll build
      - run: |
          DIFF=$(git diff ./README.md | base64)
          echo "DIFF<<EOF" >> $GITHUB_ENV
          echo $DIFF >> $GITHUB_ENV 
          echo "EOF" >> $GITHUB_ENV 
        id: diff
      - run: echo ${{ env.DIFF }}
      - if: ${{ false }}
        #if: steps.diff.outputs.result == '1'
        uses: actions-x/commit@v6
        with:
          message: "[GHA] Update REAMDE.md"
          email: handiman@users.noreply.github.com
          files: README.md

      - if: ${{ false }}
        #if: steps.diff.outputs.result == ''
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: _site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
