name: Build and Publish
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install bundler
      - run: bundler install
      - run: bundle exec jekyll build
      - run: echo "exit-code=$(git diff --quiet --exit-code ./README.md)" >> $GITHUB_OUTPUT
        id: diff
      - run: echo ${{ steps.diff.outputs.exit-code }}
      - if: ${{ false }}
        #if: steps.diff.outputs.exit-code == '1'
        uses: actions-x/commit@v6
        with:
          message: "[GHA] Update REAMDE.md"
          email: handiman@users.noreply.github.com
          files: README.md

      - if: steps.diff.outputs.exit-code == '0'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: _site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
