name: Build and Publish
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install bundler
      - run: bundler install

      - id: build
        run: |
          bundle exec jekyll build
          diff=$(git diff ./README.md)
          echo "readme-diff=<<$diff" >> $GITHUB_OUTPUT

      - if: steps.build.output.readme-diff != ''
        uses: actions-x/commit@v6
        with:
          message: "[GHA] Update REAMDE.md"
          email: handiman@users.noreply.github.com
          files: README.md

      - if: steps.build.output.readme-diff == ''
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: _site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
